function in = response_v5_input(p,cfg,maximumThrust,stopTime)
%RESPONSE_V5_INPUT Frozen flight commands; independent controller design.
mdl='Drone_Response_v5';cfg.DragRate=p.Physics.HorizontalDamping;
in=rtl_refinement_input(p,cfg,mdl);
in=in.setModelParameter('StopTime',sprintf('%.17g',stopTime));
vars=struct('Tmax',maximumThrust,...
    'replay_collective_to_pair_thrust_N',p.Physics.PairThrustScale,...
    'response_vertical_drag_rate',p.Physics.VerticalDamping,...
    'tau_m',p.Physics.MotorTimeConstant,'flight_mode',3,...
    'response_manual_enable',p.ManualEnable,...
    'response_axis_nx',p.Physics.AxisVector(1),...
    'response_axis_ny',p.Physics.AxisVector(2),...
    'response_axis_nz',p.Physics.AxisVector(3));
names=fieldnames(vars);
for k=1:numel(names),in=in.setVariable(names{k},vars.(names{k}),'Workspace',mdl);end
for id=[501,502,504]
    in=in.setBlockParameter(Simulink.ID.getFullName(sprintf('%s:%d',mdl,id)),'Threshold','0.5');
end
initial=p.RTL.InitialState;
% An autonomous-only replay starts with position-loop attitude commands.
% Manual replay instead initializes these filters from logged desired ATT.
if p.ManualEnable.Data(1)>0.5
    in=in.setBlockParameter(Simulink.ID.getFullName([mdl,':184']),'InitialConditionForFilter',...
        sprintf('%.15g',.5*(p.RTL.AttitudeDataset{1}.Data(1)-initial.phi0)));
    in=in.setBlockParameter(Simulink.ID.getFullName([mdl,':8']),'InitialConditionForFilter',...
        sprintf('%.15g',.28*(p.RTL.AttitudeDataset{2}.Data(1)-initial.theta0)));
end
end
