function metrics = summarize_flight_log_day1(flight, outputFolder)
%SUMMARIZE_FLIGHT_LOG_DAY1 Calculate reproducible measurements from the log.

arguments
    flight (1, 1) struct
    outputFolder (1, 1) string
end

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

hoverWindow = timerange(seconds(64), seconds(70), "closed");
rtlWindow = timerange(seconds(69.92), seconds(79.21), "closed");
trajectory = flight.Trajectory(flight.Trajectory.ValidPosition, :);
hoverAttitude = flight.Messages.ATT(hoverWindow, :);
hoverBattery = flight.Messages.BAT(hoverWindow, :);
hoverControl = flight.Messages.CTUN(hoverWindow, :);
hoverVibration = flight.Messages.VIBE(hoverWindow, :);
rtlControl = flight.Messages.CTUN(rtlWindow, :);

stepEast = diff(trajectory.East_m);
stepNorth = diff(trajectory.North_m);
horizontalPathLength = sum(hypot(stepEast, stepNorth));
rollRmse = sqrt(mean(hoverAttitude.Roll .^ 2));
pitchRmse = sqrt(mean(hoverAttitude.Pitch .^ 2));
positiveClimb = rtlControl.CRt(rtlControl.CRt > 0);
if isempty(positiveClimb)
    rtlClimbRate = NaN;
else
    rtlClimbRate = median(positiveClimb);
end

metricNames = [ ...
    "Log duration"; ...
    "Cumulative logged horizontal path (includes positioning jitter)"; ...
    "East span"; ...
    "North span"; ...
    "Maximum relative altitude"; ...
    "Stable-hover mean altitude"; ...
    "Stable-hover altitude standard deviation"; ...
    "Stable-hover roll RMSE about level"; ...
    "Stable-hover pitch RMSE about level"; ...
    "Stable-hover mean current"; ...
    "Stable-hover peak current"; ...
    "Stable-hover mean voltage"; ...
    "Stable-hover minimum voltage"; ...
    "Flight peak current"; ...
    "Flight minimum voltage"; ...
    "Stable-hover mean vibration X"; ...
    "Stable-hover mean vibration Y"; ...
    "Stable-hover mean vibration Z"; ...
    "RTL median positive climb rate"; ...
    "Logged mode transitions"];
values = [ ...
    seconds(trajectory.LogTime(end)); ...
    horizontalPathLength; ...
    max(trajectory.East_m) - min(trajectory.East_m); ...
    max(trajectory.North_m) - min(trajectory.North_m); ...
    max(trajectory.Up_m); ...
    mean(hoverControl.Alt); ...
    std(hoverControl.Alt); ...
    rollRmse; ...
    pitchRmse; ...
    mean(hoverBattery.Curr); ...
    max(hoverBattery.Curr); ...
    mean(hoverBattery.Volt); ...
    min(hoverBattery.Volt); ...
    max(flight.Messages.BAT.Curr); ...
    min(flight.Messages.BAT.Volt); ...
    mean(hoverVibration.VibeX); ...
    mean(hoverVibration.VibeY); ...
    mean(hoverVibration.VibeZ); ...
    rtlClimbRate; ...
    height(flight.Messages.MODE)];
units = [ ...
    "s"; "m"; "m"; "m"; "m"; "m"; "m"; "deg"; "deg"; ...
    "A"; "A"; "V"; "V"; "A"; "V"; "m/s^2"; "m/s^2"; "m/s^2"; ...
    "m/s"; "count"];

metrics = table(metricNames, values, units, ...
    'VariableNames', {'Metric', 'Value', 'Unit'});
writetable(metrics, fullfile(outputFolder, "day1_metrics.csv"));

modeTransitions = timetable2table(flight.Messages.MODE, ...
    "ConvertRowTimes", true);
modeTransitions.ModeName = modeName(modeTransitions.Mode);
writetable(modeTransitions, fullfile(outputFolder, "mode_transitions.csv"));

eventPatterns = ["Battery 1 is low"; "Battery Failsafe"; ...
    "RC8: MotorEStop HIGH"; "Crash: Disarming"];
eventMask = false(height(flight.Messages.MSG), 1);
for index = 1:numel(eventPatterns)
    eventMask = eventMask | contains(flight.Messages.MSG.Message, eventPatterns(index));
end
eventSummary = timetable2table(flight.Messages.MSG(eventMask, :), ...
    "ConvertRowTimes", true);
writetable(eventSummary, fullfile(outputFolder, "safety_events.csv"));

summaryLines = [ ...
    "# First-flight data summary"; ...
    ""; ...
    "Generated from the complete ArduPilot DataFlash log. Values in the stable-hover rows use 64-70 seconds after log start."; ...
    ""; ...
    "| Metric | Value | Unit |"; ...
    "|---|---:|---|"; ...
    compose("| %s | %.4g | %s |", metrics.Metric, metrics.Value, metrics.Unit)];
writelines(summaryLines, fullfile(outputFolder, "DAY1_FLIGHT_SUMMARY.md"));
end


function names = modeName(modeNumbers)
names = repmat("Unknown", size(modeNumbers));
names(modeNumbers == 0) = "Stabilize";
names(modeNumbers == 2) = "AltHold";
names(modeNumbers == 5) = "Loiter";
names(modeNumbers == 6) = "RTL";
end
